### ISSUE TITLE
HTML Skeleton

### ISSUE THREAD

**Issue by afzama** [RyanPersaud03/geekymoviewizard#3]
Given I visit the website
Then there should be a movie wizard generator 
So That I can receive personalized movie recommendations

## Tasks

Completed
- [x] `index.html` exists
- [x] contains multiple 'div' holding all the user questions

To Dos
- [x] Heading of Movie Wizard on Page 2
- [x] Under heading, page to display short set of instructions about the questions displayed ie "Answer the following questions about your movie preferences to receive personalized suggestions."
- [x] User Answer options should be checkboxes for questions 1, 4 and 5 with the option to select multiple checkboxes.
- [x] All questions to appear on page in a border
- [x] Create results.html to display api results

**Comment by afzama** [comment]
completed thank you @mk10100
